### PR TITLE
Copy Chex 3 Vanilla worm-dog fixes to Chex 1 and Chex 3 VM

### PR DESCRIPTION
**Pull request by MelodicSpaceship**
The modding version of Chex 3 Vanilla also includes the replacement dog sprites, and EDGE-Classic backports them to Chex Quest 1, so I think the recently added fixes should be copied over to them.

### CODE REVIEW

**Comment by LoboEire** [comment]
Can you link me to the chex 1 iwad you're using?

**Comment by MelodicSpaceship** [comment]
[chex.zip](https://github.com/user-attachments/files/15982815/chex.zip)

**Comment by LoboEire** [comment]
As the Chex expert, I wanted to ask you if you have any input on what sfx would be a better fit. Seeing a worm barking and yelping is a bit wierd ;)

**Comment by MelodicSpaceship** [comment]
I think it works well enough. If I didn't think so, I would've replaced the sounds in Chex 3 Vanilla.

**Comment by LoboEire** [comment]
All good then.

**Pull request merged**
